---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "numorph_intensityadjustment"
description: This module adjusts image intensities by correcting uneven illumination using BaSiC and addressing intensity differences between tile stacks. It measures and corrects the 95th percentile pixel intensities in overlapping regions to compensate for photo-bleaching and light attenuation.
keywords:
  - image_processing
  - intensity_adjustment
  - fluorescence_microscopy
tools:
  - "numorph":
      description: "Analysis toolbox to quantify all nuclei and nuclear markers within the mouse cortex after clearing and imaging by light-sheet microscopy"
      homepage: "https://bitbucket.org/steinlabunc/numorph/src/master/"
      documentation: "https://bitbucket.org/steinlabunc/numorph/wiki/Home"
      tool_dev_url: "https://github.com/ok37/numorph"
      doi: "10.5281/zenodo.5346838"
      licence: ["CC by 4.0"]

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  ## TODO nf-core: Delete / customise this example input
  - parameterfile:
      type: file
      description: csv file containg all parameters that numorph needs to run
  - sample:
      type: string
      description: sample name

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

authors:
  - "@CaroAMN"
maintainers:
  - "@CaroAMN"
